import type { Metadata } from "next";
import "./globals.css";
import AuthProviders from "./services/AppProviders";

export const metadata: Metadata = {
  title: "Meet Sats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <AuthProviders>{children}</AuthProviders>
      </body>
    </html>
  );
}
